export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "../../styles/bootstrap.min.css";
import "../../styles/globals.css";
import "../../styles/dashboard.css";

export default function LoginLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
